---
- hosts: omnibox
  user: root

  vars_files:
    - "{{tape_dir}}/vars/defaults.yml"
    - tape_vars.yml

  roles:
    - backend_config
    - database_load
    - unicorn_activate
    - frontend_deploy
    # - delayed_job
    # - sidekiq
    # - redis
    - monit_activate # Run Last
