default: &default
  secret_key_base: 27379f4312cf9758ddf5eb5a117ed996e9ab8d794344784bb3fc8ec3beca863efc13f18217230361e674379e671a9b645f66b0cfd306e17bb74cdc0c7a03b80c
  devise:
    :secret_key: foo_key
    :sender_email: "noreply@iamjordan.me"
    :default_devise_url: "url.com"
  cloudinary:
    cloud_name: drubmqreq
    api_key: 116897888521161
    api_secret: qyhESEITFNoMMLUP3PR10lSNXdE

development:
  <<: *default

test:
  <<: *default
